# .github/workflows/docker-image.yml
name: Build and Push Docker Image

# Controls when the action will run.
# This workflow runs on any push to the "main" branch.
on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest # The type of machine to run the job on
    permissions:
      contents: read
      packages: write # Needed to push to GitHub Packages

    steps:
    # 1. Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Log in to the GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 3. Build the Docker image and push it to the registry
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/pislissniflis/my-web-app:latest # Ensure this is all lowercase

